/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitesIndexRouteImport } from './routes/opportunites.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as OpportunitesSlugCandidaterRouteImport } from './routes/opportunites.$slug.candidater'
import { Route as AuthenticatedAdminOpportunitesNouvelleRouteImport } from './routes/_authenticated/admin.opportunites.nouvelle'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesIndexRoute = OpportunitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitesRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OpportunitesSlugCandidaterRoute =
  OpportunitesSlugCandidaterRouteImport.update({
    id: '/$slug/candidater',
    path: '/$slug/candidater',
    getParentRoute: () => OpportunitesRoute,
  } as any)
const AuthenticatedAdminOpportunitesNouvelleRoute =
  AuthenticatedAdminOpportunitesNouvelleRouteImport.update({
    id: '/admin/opportunites/nouvelle',
    path: '/admin/opportunites/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/partenaires': typeof PartenairesRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/opportunites/': typeof OpportunitesIndexRoute
  '/opportunites/$slug/candidater': typeof OpportunitesSlugCandidaterRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/opportunites/nouvelle': typeof AuthenticatedAdminOpportunitesNouvelleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/opportunites': typeof OpportunitesIndexRoute
  '/opportunites/$slug/candidater': typeof OpportunitesSlugCandidaterRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/opportunites/nouvelle': typeof AuthenticatedAdminOpportunitesNouvelleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/partenaires': typeof PartenairesRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/opportunites/': typeof OpportunitesIndexRoute
  '/opportunites/$slug/candidater': typeof OpportunitesSlugCandidaterRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/opportunites/nouvelle': typeof AuthenticatedAdminOpportunitesNouvelleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/faq'
    | '/impact'
    | '/mentions-legales'
    | '/opportunites'
    | '/partenaires'
    | '/programmes'
    | '/sitemap.xml'
    | '/opportunites/'
    | '/opportunites/$slug/candidater'
    | '/admin/'
    | '/admin/opportunites/nouvelle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/faq'
    | '/impact'
    | '/mentions-legales'
    | '/partenaires'
    | '/programmes'
    | '/sitemap.xml'
    | '/opportunites'
    | '/opportunites/$slug/candidater'
    | '/admin'
    | '/admin/opportunites/nouvelle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/faq'
    | '/impact'
    | '/mentions-legales'
    | '/opportunites'
    | '/partenaires'
    | '/programmes'
    | '/sitemap.xml'
    | '/opportunites/'
    | '/opportunites/$slug/candidater'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/opportunites/nouvelle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRoute
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ImpactRoute: typeof ImpactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OpportunitesRoute: typeof OpportunitesRouteWithChildren
  PartenairesRoute: typeof PartenairesRoute
  ProgrammesRoute: typeof ProgrammesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites/': {
      id: '/opportunites/'
      path: '/'
      fullPath: '/opportunites/'
      preLoaderRoute: typeof OpportunitesIndexRouteImport
      parentRoute: typeof OpportunitesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/opportunites/$slug/candidater': {
      id: '/opportunites/$slug/candidater'
      path: '/$slug/candidater'
      fullPath: '/opportunites/$slug/candidater'
      preLoaderRoute: typeof OpportunitesSlugCandidaterRouteImport
      parentRoute: typeof OpportunitesRoute
    }
    '/_authenticated/admin/opportunites/nouvelle': {
      id: '/_authenticated/admin/opportunites/nouvelle'
      path: '/admin/opportunites/nouvelle'
      fullPath: '/admin/opportunites/nouvelle'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOpportunitesNouvelleRoute: typeof AuthenticatedAdminOpportunitesNouvelleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOpportunitesNouvelleRoute:
    AuthenticatedAdminOpportunitesNouvelleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OpportunitesRouteChildren {
  OpportunitesIndexRoute: typeof OpportunitesIndexRoute
  OpportunitesSlugCandidaterRoute: typeof OpportunitesSlugCandidaterRoute
}

const OpportunitesRouteChildren: OpportunitesRouteChildren = {
  OpportunitesIndexRoute: OpportunitesIndexRoute,
  OpportunitesSlugCandidaterRoute: OpportunitesSlugCandidaterRoute,
}

const OpportunitesRouteWithChildren = OpportunitesRoute._addFileChildren(
  OpportunitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRoute,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ImpactRoute: ImpactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OpportunitesRoute: OpportunitesRouteWithChildren,
  PartenairesRoute: PartenairesRoute,
  ProgrammesRoute: ProgrammesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
